# Generated by Django 5.2.7 on 2025-10-10 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('departments', '0001_initial'),
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__isnull', True), ('date_end__gte', models.F('date_start')), _connector='OR'), name='event_end_gte_start_or_null'),
        ),
    ]
