# Generated by Django 6.0 on 2025-12-16 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description'),
        ('departments', '0001_initial'),
        ('events', '0004_event_created_by_event_is_published_event_locations'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_end_gte_start_or_null',
        ),
        migrations.AddField(
            model_name='event',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='events_responsible_many', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='event_end_after_start'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible',
        ),
    ]
