# Generated by Django 6.0 on 2025-12-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название подразделения')),
            ],
            options={
                'db_table': 'departament',
                'managed': False,
            },
        ),
    ]